### PR TITLE
chore(contract): comment the logic to issue sbt from the smart contract

### PR DESCRIPTION
**Pull request by leisterfrancisco**
# What does this PR do?

- Disable the ability to issue `SBT` during an election.

### CODE REVIEW

**Comment by neodanielsingh** [comment]
eosevenlotto

**Review by fagomezra — APPROVED** [review]
LGTM

**Review by xavier506 — APPROVED** [review]
LGTM

**Comment by neodanielsingh** [comment]
Regarding SBT

**Comment by leisterfrancisco** [comment]
The SBTs are going to be issued manually by the responsible team, then we are disabling the SBTs issuance from the Smart Contract for this election.

**Comment by neodanielsingh** [comment]
Ok, got it. Thanks. EYD

**Pull request merged**
